name: flutter_firebase_flutter_2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^0.1.2
  firebase_auth: 
  google_sign_in: 
  flutter_bloc: 
  equatable:
  meta:
  rxdart:
  flutter_auth_buttons:
  animate_do:
  flare_flutter:
  charts_flutter:
  flutter_sparkline: 
  flutter_staggered_grid_view:
  flutter_circular_chart:
  font_awesome_flutter:
  firebase_database:
  firebase_storage:
  intl:
  image_picker:  
  table_calendar:
  shared_preferences:
  carousel_pro:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
